### ISSUE TITLE
Can't compile the contracts

### ISSUE THREAD

**Issue by Guitlle** [aragon/dao-templates#209]
Hi, I am learning about templates with this repo. I cloned it, installed it and attempted to compile but I got the error `RangeError: Maximum call stack size exceeded`. I am using node 12 as I was experimenting with other aragon repositories. What could be causing this? Do others get the same error?

**Comment by yuetloo** [comment]
should be able to compile the contracts without error.  The github workflow in this project uses node v14 and ubuntu to compile the contracts and deploy without error. Which template did you try to compile?

**Comment by Guitlle** [comment]
I tried with the bare and membership templates which are what I'm interested in. 

If I do a simple compile I get:

```
$ npx truffle compile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ^
RangeError: Maximum call stack size exceeded
    at Object._db [as dynCall_viiiiii] (.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:12:120931)
    at invoke_viiiiii (.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:1:1117622)
    at Array.ova (.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:13:29030)
    at Object.L9a [as dynCall_vi] (.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:12:99033)
    at invoke_vi (.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:1:1114426)
    at Array.wta (.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:10:704789)
    at Object.Cfb [as dynCall_iii] (.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:12:130740)
    at invoke_iii (.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:1:1118857)
    at Array.uta (.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:10:703085)
    at Object.Xfb [as dynCall_iiiiii] (.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:12:131900)
```

Since this truncates the output, I tried doing the following and got this:

```
$ npx truffle compile 2>&1 | less 
...
...
Compiling @aragon/os/contracts/kernel/KernelProxy.sol...
Compiling @aragon/os/contracts/kernel/KernelStorage.sol...
Compiling @aragon/os/contracts/lib/ens/AbstractENS.sol...
Compiling @aragon/os/contracts/lib/ens/ENS.sol...
Compiling @aragon/os/contracts/lib/ens/PublicResolver.sol...
Compiling @aragon/os/contracts/lib/math/SafeMath.sol...
Compiling @aragon/os/contracts/lib/math/SafeMath64.sol...
Compiling @aragon/os/contracts/lib/misc/ERCProxy.sol...
Compiling @aragon/os/contracts/lib/token/ERC20.sol...
Compiling @aragon/ppf-contracts/contracts/IFeed.sol...
Compiling @aragon/templates-shared/contracts/BaseTemplate.sol...
Compiling @aragon/templates-shared/contracts/Migrations.sol...

.../dao-templates/templates/bare/node_modules/truffle/node_modules/solc/soljson.js:12
function T5a(a){...... [[[a lot of minified javascript code]]]
....
```
Maybe this is because it uses an old version of truffle? If there an easier way to develop a new template?

**Comment by Guitlle** [comment]
I was able to compile by doing this in the compile command in the package.json:

```
npx --node-arg="--stack-size=1000000" truffle compile --all
```
