### ISSUE TITLE
Can't run `scripts/create.js` or `scripts/deploy.js`

### ISSUE THREAD

**Issue by sorenrood** [aragon/dao-templates#220]
Hi! Would love some pointers here! Using node v14.0.0 and npm v8.3.1. I am trying to deploy the trust DAO template.

```
ubuntu@sorenserver:~/dao-templates/templates/trust$ npx hardhat run scripts/create.js
npm does not support Node.js v14.0.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/

/home/ubuntu/dao-templates/templates/trust/scripts/create.js:4
const { fileName } = require('@aragon/templates-shared/lib/arapp-file')(web3)
                                                                        ^
ReferenceError: web3 is not defined
    at Object.<anonymous> (/home/ubuntu/dao-templates/templates/trust/scripts/create.js:4:73)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by sorenrood** [comment]
The reference error does not go away when changing node versions.

**Comment by sorenrood** [comment]
Ah, so I've learned that you have to do `truffle exec --network gorli <input_file>`. At this point, I'm not sure what the "input file" should be...

**Comment by sorenrood** [comment]
![Screen Shot 2022-01-23 at 10 08 17 PM](https://user-images.githubusercontent.com/49735495/150730693-e8a97069-ba45-4325-b892-1e29b6f92b9d.png)

I also had to remove this line since truffle.js does not exist in @aragon/templates-shared...

**Comment by sorenrood** [comment]
I wish the deployment process was a bit more clear.

**Comment by sorenrood** [comment]
Okay so I've moved the contracts to a hardhat project and am able to compile them! Now I'm running into issues with the constructor.

**Comment by alibama** [comment]
Hi @sorenrood my belief is that you may need to use NVM to run node 12 for this
